### ISSUE TITLE
Installing orchard issue

### ISSUE THREAD

**Issue by anantapantulasa** [daniel1noble/orchaRd#7] opened 2022-08-05 20:09 UTC
Hi! I tried to install orchaRd using the code from the vignette, but it didn't work. I received the following error.

_______________________________________________________________________________________________________________________________________

> devtools::install_github("daniel1noble/orchaRd", force = TRUE)
Downloading GitHub repo daniel1noble/orchaRd@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/daniel1noble/orchaRd/tarball/HEAD' failed
_______________________________________________________________________________________________________________________________________

Any suggestions for how to fix this issue? I'm using Windows, by the way.

**Comment by daniel1noble** [comment] 2022-08-07 04:42
Hi @anantapantulasa. What version of R are you using? Can you show `sessionInfo()`? Hard to diagnose as I'm not getting that same error, so I'm not sure if its something with your configuration.

**Comment by daniel1noble** [comment] 2022-08-07 04:57
Also, just a note. Be sure to be connected to the internet before `devtools::install("daniel1noble/orchaRd", force = TRUE)`, this could be related to that error. You need to also have download `devtools` before running that code

**Comment by anantapantulasa** [comment] 2022-08-07 14:30
Hi @daniel1noble, Thanks for your response! I downloaded `devtools `and connected to the internet before running the code (I did it again, just to make sure); however, I received the same error. Do you think the "tarball/HEAD" is incorrect? `sessionInfo()` information is also below (second block of code).incorrect?

-------------------------------------------------------------------------------------------------------------------------------
> install_github("daniel1noble/orchaRd")
Downloading GitHub repo daniel1noble/orchaRd@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/daniel1noble/orchaRd/**tarball/HEAD**' failed
-------------------------------------------------------------------------------------------------------------------------------

> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
 [1] readr_2.1.2      metafor_3.4-0    metadat_1.2-0    Matrix_1.4-1    
 [5] forestplot_2.0.1 checkmate_2.1.0  magrittr_2.0.3   dplyr_1.0.9     
 [9] orchaRd_2.0      reader_1.0.6     NCmisc_1.1.6    

loaded via a namespace (and not attached):
 [1] mvtnorm_1.1-3     lattice_0.20-45   prettyunits_1.1.1
 [4] ps_1.7.1          digest_0.6.29     assertthat_0.2.1 
 [7] utf8_1.2.2        R6_2.5.1          backports_1.4.1  
[10] coda_0.19-4       ggplot2_3.3.6     pillar_1.7.0     
[13] rlang_1.0.3       rstudioapi_0.13   callr_3.7.0      
[16] mathjaxr_1.6-0    labeling_0.4.2    devtools_2.4.3   
[19] stringr_1.4.0     munsell_0.5.0     compiler_4.2.1   
[22] vipor_0.4.5       pkgconfig_2.0.3   pkgbuild_1.3.1   
[25] ggbeeswarm_0.6.0  tidyselect_1.1.2  tibble_3.1.7     
[28] fansi_1.0.3       crayon_1.5.1      tzdb_0.3.0       
[31] nlme_3.1-157      xtable_1.8-4      gtable_0.3.0     
[34] lifecycle_1.0.1   DBI_1.1.3         pacman_0.5.1     
[37] scales_1.2.0      estimability_1.4  cli_3.3.0        
[40] stringi_1.7.6     cachem_1.0.6      farver_2.1.1     
[43] proftools_0.99-3  fs_1.5.2          remotes_2.4.2    
[46] ellipsis_0.3.2    generics_0.1.3    vctrs_0.4.1      
[49] latex2exp_0.9.4   tools_4.2.1       glue_1.6.2       
[52] beeswarm_0.4.0    purrr_0.3.4       hms_1.1.1        
[55] emmeans_1.7.5     processx_3.7.0    pkgload_1.3.0    
[58] fastmap_1.1.0     colorspace_2.0-3  sessioninfo_1.2.2
[61] memoise_2.0.1     usethis_2.1.6    
-------------------------------------------------------------------------------------------------------------------------------

**Comment by daniel1noble** [comment] 2022-08-08 00:02
Odd. I’m not entirely sure what the problem is. Sorry. Seems to all work fine on Mac and RHub says Windows too.

Can you try to download and install manually: https://kbroman.org/pkg_primer/pages/build.html <https://kbroman.org/pkg_primer/pages/build.html>

You should be able to download the file from GitHub and install in your R library. I’m not sure if this will lead to other issues, but for now, it may be a temporary solution.

Dan

**Comment by daniel1noble** [comment] 2022-08-08 00:03
I also wonder whether this might be an RTools issue. You could install RTools and then try again with devtools::

https://cran.r-project.org/bin/windows/Rtools/ <https://cran.r-project.org/bin/windows/Rtools/>

Dan

**Comment by daniel1noble** [comment] 2022-08-08 10:44
@anantapantulasa I was thinning about this some more, and I had a closer look. Ok, one possible problem is that `emmeans` has yet again gone through an update. The problem with the recent update to ver. 1.8.0 is that it requires R 4.2.0>. I see you're running 4.2.1, but you have `emmeans` a version back. You may also want to try a fresh install of the `emmeans` package. very 1.8.0 still works perfectly fine with `orchaRd` (I've done all the testing just today).

**Comment by daniel1noble** [comment] 2022-08-11 01:39
Install issues seem sorted so I'm closing this issue

**Closed by daniel1noble** 2022-08-11 01:39 UTC
